// Auto-generated by openapi-typescript. Run `make generate-client` to regenerate.
export interface paths {
  "/api/system/users": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              data: SystemUser[];
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            email: string;
            password: string;
            role?: "user" | "admin";
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": {
              data: SystemUser;
            };
          };
        };
      };
    };
  };
  "/api/system/users/{id}": {
    patch: {
      parameters: {
        path: { id: string };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            role?: "user" | "admin";
            banned?: boolean;
            ban_reason?: string | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data: SystemUser;
            };
          };
        };
      };
    };
  };
}

export interface SystemUser {
  id: string;
  name: string;
  email: string;
  role: string;
  emailVerified: boolean;
  banned: boolean;
  ban_reason: string | null;
  created_at: number | null;
  updated_at: number | null;
}

export interface components {}
export interface operations {}
