/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSystemUsers"];
        put?: never;
        post: operations["createSystemUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSystemUser"];
        trace?: never;
    };
    "/api/system/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSystemSettings"];
        trace?: never;
    };
    "/api/initiatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInitiatives"];
        put?: never;
        post: operations["createInitiative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/initiatives/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInitiative"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateInitiative"];
        trace?: never;
    };
    "/api/initiatives/{slug}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveInitiative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/initiatives/{slug}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveInitiative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssues"];
        put?: never;
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateIssue"];
        trace?: never;
    };
    "/api/issues/{number}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{number}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addIssueLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{number}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeIssueLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{number}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssueComments"];
        put?: never;
        post: operations["createIssueComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch: operations["updateComment"];
        trace?: never;
    };
    "/api/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLabels"];
        put?: never;
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteLabel"];
        options?: never;
        head?: never;
        patch: operations["updateLabel"];
        trace?: never;
    };
    "/api/public/orgs/{orgSlug}/initiatives/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicInitiative"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/orgs/{orgSlug}/initiatives/{slug}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicInitiativeIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/orgs/{orgSlug}/initiatives/{slug}/issues/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/orgs/{orgSlug}/initiatives/{slug}/issues/{number}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicIssueComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSystemUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            role: string;
                            emailVerified: boolean;
                            banned: boolean;
                            ban_reason: string | null;
                            created_at: number | null;
                            updated_at: number | null;
                        }[];
                    };
                };
            };
        };
    };
    createSystemUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: email */
                    email: string;
                    password: string;
                    /**
                     * @default user
                     * @enum {string}
                     */
                    role?: "user" | "admin";
                };
            };
        };
        responses: {
            /** @description Created user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            role: string;
                            emailVerified: boolean;
                            banned: boolean;
                            ban_reason: string | null;
                            created_at: number | null;
                            updated_at: number | null;
                        };
                    };
                };
            };
        };
    };
    updateSystemUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    /** @enum {string} */
                    role?: "user" | "admin";
                    banned?: boolean;
                    ban_reason?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            email: string;
                            role: string;
                            emailVerified: boolean;
                            banned: boolean;
                            ban_reason: string | null;
                            created_at: number | null;
                            updated_at: number | null;
                        };
                    };
                };
            };
        };
    };
    getSystemSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current system settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            signups_enabled: boolean;
                        };
                    };
                };
            };
        };
    };
    updateSystemSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    signups_enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated system settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            signups_enabled: boolean;
                        };
                    };
                };
            };
        };
    };
    listInitiatives: {
        parameters: {
            query?: {
                include_archived?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of initiatives */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        }[];
                    };
                };
            };
        };
    };
    createInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    /** @default  */
                    description?: string;
                    /** @default #6b7280 */
                    color?: string;
                };
            };
        };
        responses: {
            /** @description Created initiative */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    getInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    updateInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    slug?: string;
                    description?: string;
                    color?: string;
                    is_public?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    archiveInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    unarchiveInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unarchived initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    listIssues: {
        parameters: {
            query?: {
                status?: "new" | "todo" | "doing" | "done" | "wont_fix";
                priority?: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                initiative_slug?: string;
                assignee_id?: string;
                label_id?: string;
                q?: string;
                page?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered issue list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            total: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title: string;
                    /** @default  */
                    body?: string;
                    initiative_id?: string | null;
                    /** @enum {string} */
                    priority?: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                    assignee_id?: string | null;
                    /** @default [] */
                    attachment_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Created issue */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title?: string;
                    body?: string;
                    initiative_id?: string | null;
                    /** @enum {string} */
                    priority?: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                    /** @enum {string} */
                    status?: "new" | "todo" | "doing" | "done" | "wont_fix";
                    assignee_id?: string | null;
                    attachment_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Updated issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    closeIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "done" | "wont_fix";
                };
            };
        };
        responses: {
            /** @description Closed issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    addIssueLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    label_id: string;
                };
            };
        };
        responses: {
            /** @description Label attached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeIssueLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIssueComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments on the issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            issue_id: string;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                            created_at: number;
                            updated_at: number;
                        }[];
                    };
                };
            };
        };
    };
    createIssueComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    body: string;
                    /** @default [] */
                    attachment_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Created comment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            issue_id: string;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    body: string;
                    attachment_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Updated comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            issue_id: string;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                            created_at: number;
                            updated_at: number;
                        };
                    };
                };
            };
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            color: string;
                            created_at: number;
                        }[];
                    };
                };
            };
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** @default #6b7280 */
                    color?: string;
                };
            };
        };
        responses: {
            /** @description Created label */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            color: string;
                            created_at: number;
                        };
                    };
                };
            };
        };
    };
    deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    color?: string;
                };
            };
        };
        responses: {
            /** @description Updated label */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            color: string;
                            created_at: number;
                        };
                    };
                };
            };
        };
    };
    getPublicInitiative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            organization_id: string;
                            name: string;
                            slug: string;
                            description: string;
                            color: string;
                            is_public: boolean;
                            archived_at: number | null;
                            created_at: number;
                            updated_at: number;
                        };
                        organization: {
                            id: string;
                            name: string;
                            slug: string;
                        };
                    };
                };
            };
        };
    };
    listPublicInitiativeIssues: {
        parameters: {
            query?: {
                page?: string;
                limit?: string;
            };
            header?: never;
            path: {
                orgSlug: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated issue list for a public initiative */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            total: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
    };
    getPublicIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
                slug: string;
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            number: number;
                            title: string;
                            /** @enum {string} */
                            status: "new" | "todo" | "doing" | "done" | "wont_fix";
                            /** @enum {string} */
                            priority: "lol" | "meh" | "spicy" | "on_fire" | "prod_is_down" | "an_executive_is_pissed";
                            initiative: {
                                id: string;
                                name: string;
                                slug: string;
                                color: string;
                                archived: boolean;
                            } | null;
                            assignee: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            } | null;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            labels: {
                                id: string;
                                name: string;
                                color: string;
                                created_at: number;
                            }[];
                            comment_count: number;
                            created_at: number;
                            updated_at: number;
                            closed_at: number | null;
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    listPublicIssueComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
                slug: string;
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments on a public issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            issue_id: string;
                            author: {
                                id: string;
                                name: string;
                                email: string;
                                image: string | null;
                            };
                            body: string;
                            attachments: {
                                id: string;
                                filename: string;
                                content_type: string;
                                size_bytes: number;
                                url: string;
                                uploader_id: string;
                                created_at: number;
                            }[];
                            created_at: number;
                            updated_at: number;
                        }[];
                    };
                };
            };
        };
    };
}
